language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - g++-5
      - sox

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install ..

  # downloading resource doesn't work on current cmake version
  - cd test_resource
  - curl -O https://archive.org/download/test_wav/Untitled3.wav
  - mv Untitled3.wav test1.wav
  - cd ..
  - soxi test_resource/test1.wav

  - make
  - ./src/wave/wave_tests
  - make install
