language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - debian-sid
    packages:
      - cmake
      - cmake-data
      - g++-5
      - libssl1.0.0

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install ..
  - make
  - ./src/wave/wave_tests
  - make install
